/* try{
console.log("erroe cooocr")
}
catch(error){
    console.log("error catch"+ error)

} */




try{
    console.log("this is try catch")
}
catch(error){
console.log("Error occre:here error handle by catch");

}
finally{
    console.log("kya haal chaal");
}


try {
    throw{
        Number:101,
        message:"error occured"
    }
}
catch(err){
    console.log()
}